CREATE TABLE IF NOT EXISTS documents (
  id SERIAL PRIMARY KEY,
  code VARCHAR(50) UNIQUE NOT NULL,
  title VARCHAR(255) NOT NULL,
  version VARCHAR(20) NOT NULL DEFAULT '1.0',
  status VARCHAR(30) NOT NULL DEFAULT 'Borrador',
  created_at TIMESTAMP DEFAULT NOW(),
  updated_at TIMESTAMP DEFAULT NOW()
);

ALTER TABLE documents ADD COLUMN IF NOT EXISTS discipline  VARCHAR(60);
ALTER TABLE documents ADD COLUMN IF NOT EXISTS type        VARCHAR(60);
ALTER TABLE documents ADD COLUMN IF NOT EXISTS responsible VARCHAR(120);
ALTER TABLE documents ADD COLUMN IF NOT EXISTS issue_date  DATE;
ALTER TABLE documents ADD COLUMN IF NOT EXISTS notes       TEXT;
